services:
  web-server1:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./web1.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  web-server2:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./web2.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  web-server3:
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - ./web3.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build:
      context: .
    volumes:
      - ./app:/app
    working_dir: /app
    command: python app.py
